---
- import_tasks: self-signed-certificate.yml
  tags: laravel-setup-self-signed-certificate
- import_tasks: nginx-client-cert.yml
  tags: laravel-setup-nginx-client-cert

- name: Create web root
  file:
    path: "{{ www_root }}"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ laravel_apps }}"

- name: Create logs folder of sites
  file:
    path: "{{ www_root }}/{{ item.key }}/logs"
    owner: "{{ web_user }}"
    group: "{{ web_group }}"
    mode: 0755
    state: directory
  with_dict: "{{ laravel_apps }}"

- name: Create Laravel php-fpm configuration file
  template:
    src: php-fpm.conf.j2
    dest: /etc/php/7.1/fpm/pool.d/laravel.conf
  notify: reload php-fpm

- name: Disable default PHP-FPM pool
  command: mv /etc/php/7.1/fpm/pool.d/www.conf /etc/php/7.1/fpm/pool.d/www.disabled
  args:
    creates: /etc/php/7.1/fpm/pool.d/www.disabled
  when: disable_default_pool | default(true)
  notify: reload php-fpm

- import_tasks: nginx-includes.yml
  tags: [laravel-setup-nginx-includes, laravel-setup-nginx]

- import_tasks: nginx.yml
  tags: laravel-setup-nginx

- import_tasks: supervisor.yml
  tags: laravel-setup-supervisor

- name: Setup Laravel system cron
  cron:
    name: "{{ item.key }} Laravel Artisan scheduler"
    minute: "*/1"
    user: "{{ web_user }}"
    job: "run-one php {{ www_root }}/{{ item.key }}/current/artisan schedule:run >> /dev/null 2>&1"
    cron_file: "artisan-{{ item.key | replace('.', '_') }}"
  with_dict: "{{ laravel_apps }}"
